version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:


# docker volume ls para revisar el volumen y agregarlo
# DRIVER    VOLUME NAME
#local     pgdata
